version: "3.5"
services:
  vue:
    container_name: wolpertinger-vue
    build:
      context: ./app
      dockerfile: ../Dockerfile
    ports:
      - 3000:3000
networks:
  default:
    name: wolpertinger
